before_script:
  - "bundle exec rake test_app"
script:
  - "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: jruby-19mode
      env: DB=mysql
notifications:
  recipients:
    - swrobel@gmail.com
